name: Benchmarks
on:
  push:
    branches:
      - dev

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'  # SDK Version to use. keep in line with examples/benchmarkdotnet/global.json
      - name: Run benchmark
        run: cd benchmarks/Valtuutus.Benchmarks && dotnet run -c Release --filter '*'
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.Net Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: benchmarks/Valtuutus.Benchmarks/BenchmarkDotNet.Artifacts/results/Valtuutus.Benchmarks.Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '150%'
          external-data-json-path: ./cache/benchmark-data.json
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@yanpitangui,@lucasgoveia'