name: Build and publish package to nuget
on:
  release:
    types: [created]
  workflow_dispatch: 

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.x'
      - name: Install dotnet cake
        run: |
          dotnet tool install -g Cake.Tool        
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          key: nuget-${{ hashFiles('Directory.Packages.props') }}
          path: ~/.nuget/packages   
      - name: Build the project and publish package
        run: |
          dotnet cake
